apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-sample-app-demo
  labels:
    app: python-sample-app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-sample-app-demo
  template:
    metadata:
      labels:
        app: python-sample-app-demo
    spec:
      containers:
      - name: pytho-app
        image: python-sample-app-demo:v1
        imagePullPolicy: Never
        # Mount the ConfigMap volume inside the container at /opt
        volumeMounts:   #then mount the volume that is nothong but reading it in pod level
         - name: db-connection
           mountPath: /opt
        
        # Read value from ConfigMap
#        env:
#        - name: DB-PORT
#          valueFrom:
#           configMapKeyRef:
#            name: python-config # ConfigMap name
#           key: db-port        # Key inside ConfigMap
        ports:
        - containerPort: 8000
        # Create a volume from the ConfigMap
      volumes:  #create volume/storage first
        - name: db-connection
          configMap:
           name: python-config
